package:
  name: ntd-trachoma
  version: 0.0.2

source:
  git_rev: a5ba739bd2e9cf721710fca6277493362dc2e8c1
  git_url: https://github.com/NTD-Modelling-Consortium/ntd-model-trachoma.git

build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps

requirements:
  build:
    - python
    - setuptools

  run:
    - python>=3.6
    - numpy
    - pandas
    - joblib
    - google-cloud-storage
    - matplotlib
    - openpyxl

test:
  imports:
    - trachoma
