#!/usr/bin/env bash

if [[ ! -f "${1}" ]] ; then
    echo "usage: $0 <instance-to-group-map file path>"
    exit 1
fi

while read -r entry
do
    instance=$( echo $entry | cut -f 1 -d : )
    group=$( echo $entry | cut -f 2 -d : )
    zone=$( echo ${instance} | awk -F '-' '{print $2"-"$3"-"$4}' )

    echo "-> running groups ${group} on instance ${instance} in zone ${zone}"
    echo gcloud compute ssh "${instance}" --zone "${zone}" --command "( cd ntd-model-trachoma && git pull origin master && bash scripts/nohup-group.bash ${group} && ls -1 run_group_*)"
   # gcloud compute ssh "${instance}" --zone "${zone}" --command "( cd ntd-model-trachoma && git pull origin master && bash scripts/nohup-group.bash ${group} && ls -1 run_group_*)"
    echo

done < "${1}"

